apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      containers:
      - name: appointment-service
        image: mediconnect/appointment-service:v3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4003
        envFrom:
        - configMapRef:
            name: mediconnect-config
        - secretRef:
            name: mediconnect-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: appointment-service
spec:
  selector:
    app: appointment-service
  ports:
    - protocol: TCP
      port: 4003
      targetPort: 4003
