apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctor-service
  template:
    metadata:
      labels:
        app: doctor-service
    spec:
      containers:
      - name: doctor-service
        image: mediconnect/doctor-service:v3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4002
        envFrom:
        - configMapRef:
            name: mediconnect-config
        - secretRef:
            name: mediconnect-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: doctor-service
spec:
  selector:
    app: doctor-service
  ports:
    - protocol: TCP
      port: 4002
      targetPort: 4002
