apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-service
  template:
    metadata:
      labels:
        app: patient-service
    spec:
      containers:
      - name: patient-service
        image: mediconnect/patient-service:v3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4001
        envFrom:
        - configMapRef:
            name: mediconnect-config
        - secretRef:
            name: mediconnect-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: patient-service
spec:
  selector:
    app: patient-service
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001
