apiVersion: v1
kind: Secret
metadata:
  name: mediconnect-secrets
type: Opaque
stringData:
  MONGODB_URI: "mongodb+srv://REPLACE_USER:REPLACE_PASS@cluster0.example.mongodb.net/?appName=Cluster0"
  JWT_SECRET: "replace_with_long_random_secret_min_32_chars"
  REFRESH_SECRET: "replace_with_another_long_random_secret_min_32_chars"
  STRIPE_SECRET_KEY: "sk_test_REPLACE_ME"
  STRIPE_WEBHOOK_SECRET: "whsec_REPLACE_ME"
  AGORA_APP_ID: "REPLACE_ME"
  AGORA_APP_CERTIFICATE: "REPLACE_ME"
  HF_API_TOKEN: "hf_REPLACE_ME"
  SMTP_USER: "REPLACE_ME@gmail.com"
  SMTP_PASS: "REPLACE_ME"
  TWILIO_SID: "AC_REPLACE_ME"
  TWILIO_TOKEN: "REPLACE_ME"
  TWILIO_FROM: "+10000000000"
  INTERNAL_SERVICE_SECRET: "REPLACE_ME"
