apiVersion: v1
kind: Secret
metadata:
  name: mediconnect-secrets
type: Opaque
stringData:
  MONGODB_URI: "mongodb+srv://dinuwaperera10:dinuwa123@cluster0.mndhh.mongodb.net/?appName=Cluster0"
  JWT_SECRET: "your_jwt_secret_key_here"
  REFRESH_SECRET: "your_refresh_secret_key_here"
  STRIPE_SECRET_KEY: "sk_test_your_stripe_secret_key"
  STRIPE_WEBHOOK_SECRET: "your_webhook_secret"
  AGORA_APP_ID: "your_agora_app_id"
  AGORA_APP_CERTIFICATE: "your_agora_app_certificate"
  HF_API_TOKEN: "hf_your_hugging_face_token"
  SMTP_USER: "your_email@gmail.com"
  SMTP_PASS: "your_app_specific_password"
  TWILIO_SID: "your_twilio_sid"
  TWILIO_TOKEN: "your_twilio_token"
  TWILIO_FROM: "+12602613403"
  INTERNAL_SERVICE_SECRET: "mediconnect_secret_2024"
