'use client';
import { useState } from 'react';
import { Plus, Trash2, Download } from 'lucide-react';
import toast from 'react-hot-toast';
import { doctorApi } from '@/src/entities/doctor/api';
import { appointmentApi } from '@/src/entities/appointment/api';
import { Modal } from '@/src/shared/ui/Modal';
import { Button } from '@/src/shared/ui/Button';
import { Input } from '@/src/shared/ui/Input';

const FREQUENCIES = ['Once daily', 'Twice daily', 'Three times daily', 'Every 8 hours', 'Every 12 hours', 'As needed', 'Weekly'];

interface Medication {
  name: string;
  dosage: string;
  frequency: string;
  durationDays: number;
  instructions: string;
}

interface Props {
  isOpen: boolean;
  onClose: () => void;
  appointmentId: string;
  patientId: string;
  patientName?: string;
  doctorName?: string;
  onCompleted?: () => void;
}

const emptyMed = (): Medication => ({
  name: '', dosage: '', frequency: 'Once daily', durationDays: 7, instructions: '',
});

export function IssuePrescriptionModal({
  isOpen, onClose, appointmentId, patientId, patientName, doctorName, onCompleted,
}: Props) {
  const [meds,   setMeds]   = useState<Medication[]>([emptyMed()]);
  const [notes,  setNotes]  = useState('');
  const [saving, setSaving] = useState(false);

  const updateMed = (i: number, field: keyof Medication, value: string | number) =>
    setMeds((prev) => prev.map((m, idx) => idx === i ? { ...m, [field]: value } : m));

  const addMed    = () => setMeds((prev) => [...prev, emptyMed()]);
  const removeMed = (i: number) => setMeds((prev) => prev.filter((_, idx) => idx !== i));

  const handleSave = async () => {
    const invalid = meds.some((m) => !m.name.trim() || !m.dosage.trim());
    if (invalid) { toast.error('Fill name and dosage for all medications'); return; }

    setSaving(true);
    try {
      await doctorApi.issuePrescription({ appointmentId, patientId, medications: meds, notes });
      await appointmentApi.updateStatus(appointmentId, 'completed', notes);
      toast.success('Prescription issued & appointment completed');
      onCompleted?.();
      onClose();
    } catch (err: unknown) {
      toast.error(err instanceof Error ? err.message : 'Failed to save prescription');
    } finally {
      setSaving(false);
    }
  };

  const handleDownloadPdf = async () => {
    // Dynamic import – jsPDF is large, keep it out of initial bundle
    const [{ jsPDF }, { default: autoTable }] = await Promise.all([
      import('jspdf'),
      import('jspdf-autotable'),
    ]);

    const doc   = new jsPDF();
    const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
    const teal  = [13, 148, 136] as [number, number, number];

    // Header
    doc.setFillColor(...teal);
    doc.rect(0, 0, 210, 28, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text('MediConnect', 14, 12);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('Digital Prescription', 14, 20);
    doc.text(`Dr. ${doctorName ?? 'Doctor'} | ${today}`, 210 - 14, 20, { align: 'right' });

    // Patient section
    doc.setTextColor(30, 30, 30);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text('Patient', 14, 38);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.text(`Name: ${patientName ?? patientId}`, 14, 46);
    doc.text(`Appointment ID: ${appointmentId}`, 14, 52);

    // Medications table
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.text('Prescribed Medications', 14, 64);

    autoTable(doc, {
      startY: 68,
      head: [['Medication', 'Dosage', 'Frequency', 'Duration (days)', 'Instructions']],
      body: meds.map((m) => [m.name, m.dosage, m.frequency, String(m.durationDays), m.instructions || '—']),
      headStyles: { fillColor: teal, textColor: 255, fontStyle: 'bold' },
      alternateRowStyles: { fillColor: [240, 253, 252] },
      styles: { fontSize: 9, cellPadding: 3 },
    });

    // Doctor notes
    const afterTableY = (doc as jsPDF & { lastAutoTable?: { finalY?: number } }).lastAutoTable?.finalY ?? 120;
    if (notes.trim()) {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(11);
      doc.text('Doctor Notes', 14, afterTableY + 10);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.text(doc.splitTextToSize(notes, 180), 14, afterTableY + 17);
    }

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(120, 120, 120);
    doc.text('This is a digital prescription generated by MediConnect. It is not a substitute for professional medical advice.', 14, 285);

    doc.save(`prescription-${appointmentId.slice(-8)}.pdf`);
  };

  return (
    <Modal isOpen={isOpen} onClose={onClose} title="Issue Prescription" size="lg">
      <div className="space-y-5 max-h-[70vh] overflow-y-auto pr-1">

        {/* Medications */}
        <div className="space-y-4">
          {meds.map((med, i) => (
            <div key={i} className="rounded-lg border border-gray-200 bg-gray-50 p-4 space-y-3">
              <div className="flex items-center justify-between">
                <span className="text-sm font-semibold text-gray-700">Medication {i + 1}</span>
                {meds.length > 1 && (
                  <button onClick={() => removeMed(i)} className="text-red-400 hover:text-red-600 transition-colors">
                    <Trash2 className="h-4 w-4" />
                  </button>
                )}
              </div>
              <div className="grid grid-cols-2 gap-3">
                <Input
                  label="Name *" placeholder="e.g. Amoxicillin"
                  value={med.name} onChange={(e) => updateMed(i, 'name', e.target.value)}
                />
                <Input
                  label="Dosage *" placeholder="e.g. 500mg"
                  value={med.dosage} onChange={(e) => updateMed(i, 'dosage', e.target.value)}
                />
              </div>
              <div className="grid grid-cols-2 gap-3">
                <div className="flex flex-col gap-1">
                  <label className="text-sm font-medium text-gray-700">Frequency</label>
                  <select
                    value={med.frequency}
                    onChange={(e) => updateMed(i, 'frequency', e.target.value)}
                    className="rounded-lg border border-gray-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-teal-500"
                  >
                    {FREQUENCIES.map((f) => <option key={f}>{f}</option>)}
                  </select>
                </div>
                <Input
                  label="Duration (days)" type="number"
                  value={String(med.durationDays)}
                  onChange={(e) => updateMed(i, 'durationDays', Number(e.target.value))}
                />
              </div>
              <Input
                label="Instructions" placeholder="e.g. Take after meals"
                value={med.instructions} onChange={(e) => updateMed(i, 'instructions', e.target.value)}
              />
            </div>
          ))}
        </div>

        <button
          onClick={addMed}
          className="flex items-center gap-2 text-sm font-medium text-teal-600 hover:text-teal-700 transition-colors"
        >
          <Plus className="h-4 w-4" /> Add Medication
        </button>

        {/* Doctor notes */}
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">Doctor Notes</label>
          <textarea
            rows={3}
            value={notes}
            onChange={(e) => setNotes(e.target.value)}
            placeholder="Additional clinical notes…"
            className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-teal-500 resize-none"
          />
        </div>

        {/* Actions */}
        <div className="flex flex-wrap gap-3 pt-2">
          <Button isLoading={saving} onClick={handleSave}>
            Save & Complete Appointment
          </Button>
          <Button variant="secondary" onClick={handleDownloadPdf}>
            <Download className="h-4 w-4" /> Download PDF
          </Button>
          <Button variant="ghost" onClick={onClose} disabled={saving}>Cancel</Button>
        </div>
      </div>
    </Modal>
  );
}
